# -*- coding: utf-8 -*-
"""practice 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1twYkXLNd7bRIqEWayQyRJ_8MHdw7ljly

# faiza talpur
# Course: python
# practice = 01
# date: 8-10-2025
"""

first_name= "faiza"
last_name="talpur"
age= "30"
occupation= "primary school teacher"
city= "talhar"
district= "badin"
country= "pakistan"
course_name= "python"

print("My name is",first_name,last_name)
print("I am",age,"years old")
print("I am a",occupation)
print("I live in",city,district,country)
print("I am learning",course_name)